apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: dev
spec:
  storageClassName: local-storage  # Должно строго совпадать с именем в PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi                 # Запрашиваем 2ГБ из доступных 5ГБ
