apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi         # Объем хранилища
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce        # Диск может быть смонтирован на запись только одной нодой
  persistentVolumeReclaimPolicy: Retain # Сохранять данные на диске после удаления PVC
  storageClassName: local-storage        # Имя класса для связывания с PVC
  hostPath:
    path: "/mnt/data"    # Папка внутри контейнера/ноды minikube
