apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-app
  namespace: dev
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: redis-db
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        # Шаг А: Монтируем диск внутрь контейнера Redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      # Шаг Б: Описываем, какой именно PVC мы подключаем к поду
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
