apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod
  namespace: dev
spec:
  containers:
  - name: web-tester
    image: nginx:1.25-alpine
    volumeMounts:
    - name: my-volume
      mountPath: /usr/share/nginx/html # Папка внутри контейнера
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: task-pvc            # Подключаем созданный выше PVC
