apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  namespace: dev
spec:
  storageClassName: standard    
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi     
